### ISSUE TITLE
dev-python/rectangle-packer-2.0.2: missing dependencies

### ISSUE THREAD

**Issue by u3shit** [houseofsuns/pypi#1]
You said in the readme to open issues when there are problems with the dependencies, so here they are. I tried to install rectangle-packer, but the install failed because of a missing dependency. Rectangle-packer requires `Cython<3.0.0` but it is not in the ebuild (and I only had cython 3 installed).
https://github.com/Penlect/rectangle-packer/blob/master/setup.py#L62

**Comment by houseofsuns** [comment]
As this overlay only provides a single version of each package I decided to drop all version ranges from dependency specifications. This was a bit rash. A sensible way might be to add version ranges back in for packages which are available in the main tree. I'll have to look at how that can be effected.

**Comment by houseofsuns** [comment]
However in this case this information is only available after unpacking the source and not via the PyPI-API [1]. So there is probably nothing that can be done in this specific case.

[1]  https://pypi.org/pypi/rectangle-packer/json

**Comment by u3shit** [comment]
I see. I guess that dependency is only really needed for building and not when downloading a binary package.

**Comment by houseofsuns** [comment]
The overlay now contains version bound information for main tree packages.
