### ISSUE TITLE
dev-python/vorta missing runtime dependencies

### ISSUE THREAD

**Issue by 10leej** [houseofsuns/pypi#3]
Missing these which are available in ::gentoo

dev-python/peewee
dev-python/PyQt6
dev-python/psutil

**Comment by houseofsuns** [comment]
dev-python/peewee and dev-python/psutil are in the overlay.

dev-python/PyQt6 is also there, but named dev-python/pyqt6 with lowercase letters. I think this is an artifact of the processing pipeline of https://github.com/pypi-data which this uses under the hood. I'll have to poke a bit how to reverse the normalization here, i.e. where to acquire the definite name of a package (a similar problem exists with hyphens and underscores which are all normalized towards hyphens by pypi-data).

**Comment by houseofsuns** [comment]
The naming thing is actually somewhere between very pragmatic and borderline broken as things  get automatically aliased on PyPI. The overlay now contains the packages under their real names except if there already exists a different name in ::gentoo. Also all dependencies are canonicalized as portage does not play well with the aliasing trickery.
