### ISSUE TITLE
dev-python/nerfstudio: dependency open3d referenced misnamed in ebuild

### ISSUE THREAD

**Issue by aTosser** [houseofsuns/pypi#4]
emerge: there are no ebuilds to satisfy "dev-python/open3d[python_targets_python3_10(-)?,python_targets_python3_11(-)?,python_targets_python3_12(-)?]".
(dependency required by "dev-python/nerfstudio-1.0.0::pypi" [ebuild])

 dev-python/open3d-python is the actual package name in ::pypi 
 
 Ebuild should be fixed or dep should be renamed.

**Comment by houseofsuns** [comment]
The root problem here is that open3d does not provide source files via PyPI and thus gets dropped by the overlay generator. I pinged the corresponding [upstream issue](https://github.com/isl-org/Open3D/issues/5050) but don't know how successful this will be.
Alternatively I'm considering adding a wheel-only install option, but that will need some major rework.

PS: open3d-python seems to be the old name of open3d and did provide source files and thus does appear in the overlay but only with a rather ancient version.

**Comment by houseofsuns** [comment]
The overlay now contains the option to install wheels if no sdist is available.
